import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import {StockViewWrapper} from "@/ui/sideNavigation/StockViewWrapper";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className} >
          <div className="flex h-screen">
            <div className="w-80 bg-gray-800 h-full">
                <StockViewWrapper />
            </div>
            <div className="flex-1 p-4">
                {children}
            </div>
          </div>
      </body>
    </html>
  )
}
