// dashboard/layout.tsx
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { StockViewWrapper } from "@/ui/sideNavigation/StockViewWrapper";
import TopNavBar from "@/ui/topNavigation/TopNavBar";
import {AccountsProvider} from "@/contexts/AccountsContext";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <div className={inter.className}>
            <div className="flex flex-col h-screen">
                <div className="flex w-full">
                    <div className="w-80 bg-gray-800">
                        <StockViewWrapper />
                    </div>
                    <div className="flex-1">
                        <TopNavBar />
                    </div>
                </div>
                <div className="flex flex-1">
                    <div className="w-80 bg-gray-800 h-full" /> {/* Empty div for sidebar space */}
                    <div className="flex-1 p-4">
                        <AccountsProvider>
                            {children} {/* Main content */}
                        </AccountsProvider>
                    </div>
                </div>
            </div>
        </div>
    )
}
